
ALTER TABLE public.venue_map_references
  ADD COLUMN IF NOT EXISTS source_file_url TEXT,
  ADD COLUMN IF NOT EXISTS source_mime_type TEXT,
  ADD COLUMN IF NOT EXISTS source_page INT,
  ADD COLUMN IF NOT EXISTS natural_width INT,
  ADD COLUMN IF NOT EXISTS natural_height INT,
  ADD COLUMN IF NOT EXISTS crop_x NUMERIC,
  ADD COLUMN IF NOT EXISTS crop_y NUMERIC,
  ADD COLUMN IF NOT EXISTS crop_w NUMERIC,
  ADD COLUMN IF NOT EXISTS crop_h NUMERIC;
