
ALTER TABLE public.layout_template_booths
  ADD COLUMN IF NOT EXISTS price NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS is_electric BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_premium BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_reserved BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.event_booths
  ADD COLUMN IF NOT EXISTS is_electric BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_premium BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_reserved BOOLEAN NOT NULL DEFAULT false;
